<?php

/**
* Configuration for webgrind
*/
class Webgrind_Config{
	/**
	* Regex that matches the trace files generated by xdebug
	*/
	static $xdebugOutputFormat = '/^cachegrind\.out\.[0-9]+$/';
	
	/**
	* Directory to search for trace files
	*/
	static $xdebugOutputDir = '/tmp/';
	
	/**
	* Writable dir for information storage
	*/
	static $storageDir = '/tmp/';
		
	/**
	* Suffix for preprocessed files
	*/
	static $preprocessedSuffix = '.prep';
	
	/**
	 * Default timezone
	 */
	static $defaultTimezone = 'Europe/Copenhagen';
	/**
	 * Date format
	 */
	static $dateFormat = 'Y-m-d H:i:s';
	
	static $defaultCostformat = 'percentual';
	
	static $defaultFunctionPercentage = 90;
	
	static $defaultHideInternalFunctions = false;
	
	/**
	* sprintf compatible format for generating links to source files. 
	* %1$s will be replaced by the full path name of the file
	* %2$d will be replaced by the linenumber
	*/
	static $fileUrlFormat = 'index.php?op=fileviewer&file=%1$s&line=%2$d'; // Built in fileviewer
	//static $fileUrlFormat = 'txmt://open/?url=file://%1$s&line=%2$d'; // Textmate
	//static $fileUrlFormat = 'file://%1$s'; // ?
		
}
