<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<script src="js/jquery.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.scrollTo.js" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" href="styles/style.css" />
	<title>
		webgrind - fileviewer: <?php echo $file?>
	</title>
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function() { 
			$.scrollTo.defaults.offset = {left:0, top:-200 };
			$.scrollTo($('#line_emph'));
		});

	</script>
	
</head>
<body>
    <div id="head">
        <div id="logo">
            <h1>webgrind<sup style="font-size:10px">v<?php echo Webgrind_Config::$webgrindVersion?></sup></h1>
            <p>profiling in the browser</p>
        </div>
        <div style="clear:both;"></div>
    </div>
    <div id="main">
    	<h2><?php echo $file?></h2>
        <br>
    	<code style="overflow-x: auto; white-space: nowrap">
        <?php if ($message==''):?>

    	<?php 
    	    $syntax = explode('<br />', str_replace(array('<code>', '</code>'), '', highlight_file($file, true)));
            foreach ($syntax as $num => $string): $num++;?>
                <span class="num" <?php if ($num==$line):?>id="line_emph"<?php endif; ?>><?php echo $num ?></span>
    			<?php echo $string; ?>
    			<br />
            <? endforeach;
    	?>
    	</code>
        <?php else:?>
        	<p><b><?php echo $message?></b></p>
        <?php endif?>
    </div>
</body>
</html>