<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<title>webgrind</title>
	<link rel="stylesheet" type="text/css" href="styles/style.css" />
	<script src="js/jquery-1.2.3.pack.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.blockUI.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.tablesorter.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/jquery.selectboxes.js" type="text/javascript" charset="utf-8"></script>
	<script src="js/sprintf.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		var fileUrlFormat = '<?=Webgrind_Config::$fileUrlFormat?>';
		var currentDataFile = null;
		var callInfoLoaded = new Array();
		function getOptions(){
			options = new Object();
			options.dataFile = $("#dataFile").val();
			options.costFormat = $('#costFormat').val();
			options.showFraction = $("#showFraction").val();
			options.hideInternals = $('#hideInternals').attr('checked') ? 1 : 0;
			return options;
		}
		
		function update(){
			vars = getOptions();
			vars.op = 'function_list';
			$.getJSON("index.php",
				vars,
				function(data){
					callInfoLoaded = new Array();
					$("#function_table tbody").empty();
					for(i=0;i<data.functions.length;i++){
						callInfoLoaded[data.functions[i].nr] = false;
						$("#function_table tbody").append(functionTableRow(data.functions[i]));
					}
					currentDataFile = data.dataFile;
					$("#data_file").html(data.dataFile);
					$("#invoke_url").html(data.invokeUrl);
					$("#mtime").html(data.mtime);
					$("#selfcost_sum").html(data.summedRunTime);
					
					$("#hello_message").hide();
					$("#trace_view").show();
					
					$("#function_table").trigger('update');
					$("#function_table").trigger("sorton",[[[3,1]]]); 
				}
			);
		}
		
		function reloadFilelist(){
			$.getJSON("index.php",
				{'op':'file_list'},
				function(data){
					options = new Object();
					for(i=0;i<data.length;i++){
						options[data[i]['filename']] = data[i]['invokeUrl']+' ('+data[i]['filename']+')';
					}
					$("#dataFile").removeOption(/[^0]/);
					$("#dataFile").addOption(options, false);

				}
			);
		}
		
		function loadCallInfo(functionNr){			
			$.getJSON("index.php",
				{'op':'callinfo_list', 'file':currentDataFile, 'functionNr':functionNr, 'costFormat':$("#costFormat").val()},
				function(data){
					
					if(!callInfoLoaded[functionNr]){
						if(data.invocations.length>0)
							$("#callinfo_area_"+functionNr).append(callInfoTable(functionNr));
						if(data.calledByHost){
							$("#callinfo_area_"+functionNr).append('Called by script host');						
						}
						
					}					
					
					for(i=0;i<data.invocations.length;i++){
						$("#callinfo_table_"+functionNr+" tbody").append(callInfoTableRow(i, data.invocations[i]));
					}
					
					if(data.invocations.length>0){				
						$("#callinfo_table_"+functionNr).tablesorter({
							widgets: ['zebra'],
							headers: { 
					            3: { 
					                sorter: false 
					            }
					        }							
						});
						$("#callinfo_table_"+functionNr).bind("sortStart",sortBlock).bind("sortEnd",$.unblockUI);
						$("#callinfo_table_"+functionNr).trigger("sorton",[[[2,1]]]); 
						
						
					} 
					
					callInfoLoaded[functionNr] = true;
				}
			);				
		
		}
		
		function callInfoTable(functionNr){
			return '<table class="tablesorter" id="callinfo_table_'+functionNr+'" cellspacing="0"> \
						<thead><tr><th>Called from</th><th>Count</th><th>Total Call Cost</th><th> </th></tr></thead> \
						<tbody> \
						</tbody> \
					</table> \
			';
		}
		
		function callInfoTableRow(nr,data){
			return '<tr> \
						<td>'+data.callerFunctionName+' @ '+data.line+'</td> \
						<td class="nr">'+data.callCount+'</td> \
						<td class="nr">'+data.summedCallCost+'</td> \
						<td><a title="Open file and show line" href="'+sprintf(fileUrlFormat,data.callerFile,data.line)+'" target="_blank"><img src="img/file_line.png" alt="O"/></a></td> \
					</tr>';
			
		}
		
		function toggleCallInfo(functionNr){
			if(!callInfoLoaded[functionNr]){
				loadCallInfo(functionNr);
			}					
			
			$("#callinfo_area_"+functionNr).toggle();
			current = $("#fold_marker_"+functionNr).get(0).src;
			if(current.substr(current.lastIndexOf('/')+1) == 'right.gif')
				$("#fold_marker_"+functionNr).get(0).src = 'img/down.gif';
			else
				$("#fold_marker_"+functionNr).get(0).src = 'img/right.gif';
		}
		
		function functionTableRow(data){
			openLink = (data.file=='php:internal')?'':'<a title="Open file" href="'+sprintf(fileUrlFormat,data.file,-1)+'" target="_blank"><img src="img/file.png" alt="O"/></a>';
			return '<tr> \
						<td> \
							<a href="javascript:toggleCallInfo('+data.nr+')"> \
								<img id="fold_marker_'+data.nr+'" src="img/right.gif" />&nbsp;&nbsp;'+data.functionName+' \
							</a> \
							<div class="callinfo_area" id="callinfo_area_'+data.nr+'"></div> \
						</td> \
						<td>'+openLink+'</td> \
						<td class="nr">'+data.invocationCount+'</td> \
						<td class="nr">'+data.summedSelfCost+'</td> \
						<td class="nr">'+data.summedInclusiveCost+'</td> \
					</tr> \
			';
		}
		
		function sortBlock(){
			$.blockUI('<h1>Sorting...</h1>');
		}
		
		
		$(document).ready(function() { 
			$.blockUI.defaults.pageMessage = '<h1>Loading...</h1><p>Loading information from server. If the callgrind file is large this may take some time</p>';
			$.blockUI.defaults.overlayCSS =  { backgroundColor: '#fff', opacity: '0' }; 
			$.blockUI.defaults.fadeIn = 0;
			$.blockUI.defaults.fadeOut = 0;
			$().ajaxStart($.blockUI).ajaxStop($.unblockUI);
			$("#function_table").tablesorter({
				widgets: ['zebra'],
				sortInitialOrder: 'desc',
				headers: { 
		            1: { 
		                sorter: false 
		            }
		        }
			});
			$("#function_table").bind("sortStart",sortBlock).bind("sortEnd",$.unblockUI);
			
		});
		
	</script>
</head>
<body>
<div id="head">
    <h1>webgrind<sup style="font-size:10px">v0.5</sup></h1>
    <p>profiling in the browser</p>
</div>
<div id="options">
    <form method="get" onsubmit="update();return false">
    	<div style="float:right;margin-left:10px">
    	    <input type="submit" value="update" />
    	</div>
    	<div style="float:right;">
    		<label style="margin:0 5px">as</label>
    		<select id="costFormat" name="costFormat">
    		    <option value="percentual" <?=(Webgrind_Config::$defaultCostformat=='percentual') ? 'selected' : ''?>>percentual</option>
    		    <option value="absolute" <?=(Webgrind_Config::$defaultCostformat=='absolute') ? 'selected' : ''?>>absolute</option>
    		</select> values
    	</div>
    	<div style="float:right;">
    		<label style="margin:0 5px">of</label>
    		<select id="dataFile" name="dataFile" style="width:200px">
    			<option value="0">Auto (newest)</option>
    			<?foreach(Webgrind_FileHandler::getInstance()->getTraceList() as $trace):?>
    				<option value="<?=$trace['filename']?>"><?=$trace['invokeUrl']?> (<?=$trace['filename']?>)</option>
    			<?endforeach;?>
    		</select>
			<img class="list_reload" src="img/reload.gif" onclick="reloadFilelist()"/>
    	</div>
    	<div style="float:right">
    		<label style="margin:0 5px">Show</label>
    		<select id="showFraction" name="showFraction">
    			<?for($i=100; $i>0; $i-=10):?>
    			<option value="<?=$i/100?>" <?if($i==Webgrind_Config::$defaultFunctionPercentage):?>selected="selected"<?endif;?>><?=$i?>%</option>
    			<?endfor;?>
    		</select>
    	</div>
    	<div style="clear:both;"></div>    	
    	<div style="margin:0 45px">
    	    <input type="checkbox" name="hideInternals" value="1" <?=(Webgrind_Config::$defaultHideInternalFunctions==1) ? 'checked' : ''?> id="hideInternals">
    	    <label for="hideInternals">Hide PHP functions</label>
    	</div>
    </form>
</div>
<div style="clear:both;"></div>
<div class="hr"></div>
<div id="trace_view">
	<h2 id="invoke_url"></h2>
	<div style="float:left;">
	    <span id="data_file"></span> @ <span id="mtime"></span>
	</div>
	<div style="float:right;">
	    Total Time : <span id="selfcost_sum"></span> µs
	</div>
	<div style="clear:both"></div>
	<table class="tablesorter" id="function_table" cellspacing="0">
		<thead><tr><th>Function</th><th> </th><th>Invocation Count</th><th>Total Self Cost</th><th>Total Inclusive Cost</th></tr></thead>
		<tbody>
		</tbody>
	</table>
</div>
<h2 id="hello_message">Select a cachegrind file above</h2>
<div id="footer">
    Copyright © 2008 Jacob Oettinger &amp; Joakim Nygård. <a href="http://code.google.com/p/webgrind/">webgrind homepage</a>
</div>
</body>
</html>